# Generated by Django 4.0.3 on 2022-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('completed', 'Выполнена'), ('cancel', 'Отмена'), ('refusal', 'Отказ')], default='new', max_length=16),
        ),
    ]
